import { describe, it, expect } from 'vitest';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { worlds, worldsForGrade } from './worlds';
import { allGenerators } from './generators';
import { badges } from './badges';
import { GRADE_IDS } from '../types/game';

/**
 * The content contract: a checked-in snapshot of every identifier a saved
 * student profile depends on.
 *
 * Progress is keyed by level id, world id, badge id and generator id — never by
 * question id. Renaming or deleting any of those four SILENTLY destroys real
 * progress: stars vanish, a level reads as unplayed, an earned badge becomes
 * re-earnable, review history for a skill is lost. There is no error at the
 * time; the damage only shows up on a student's device days later.
 *
 * So the check lives here rather than in a code review checklist. Adding
 * content is always allowed. Removing, renaming, reordering, or making a level
 * harder to pass fails the build, and the only way through is to regenerate
 * this snapshot on purpose:
 *
 *     npm run contract:update
 *
 * which makes breaking a student's save a deliberate, reviewable act.
 */

const CONTRACT_PATH = fileURLToPath(new URL('./contentContract.json', import.meta.url));

interface ContentContract {
  note: string;
  /** Ordered world ids per grade. Unlocking chains by position. */
  worldsByGrade: Record<string, string[]>;
  /** Ordered level ids per world. Unlocking chains by position. */
  levelsByWorld: Record<string, string[]>;
  /** Pass mark per level; raising one retroactively un-passes students. */
  passThresholds: Record<string, number>;
  badgeIds: string[];
  generatorIds: string[];
}

function currentContract(): ContentContract {
  const worldsByGrade: Record<string, string[]> = {};
  for (const grade of GRADE_IDS) {
    worldsByGrade[String(grade)] = worldsForGrade(grade).map((w) => w.id);
  }

  const levelsByWorld: Record<string, string[]> = {};
  const passThresholds: Record<string, number> = {};
  for (const world of worlds) {
    levelsByWorld[world.id] = world.levels.map((l) => l.id);
    for (const level of world.levels) passThresholds[level.id] = level.passThreshold;
  }

  return {
    note: 'Generated by npm run contract:update. See contentContract.test.ts before editing by hand.',
    worldsByGrade,
    levelsByWorld,
    passThresholds,
    badgeIds: badges.map((b) => b.id),
    generatorIds: allGenerators.map((g) => g.id).sort(),
  };
}

const live = currentContract();

// `npm run contract:update` regenerates the snapshot instead of asserting.
if (process.env.UPDATE_CONTENT_CONTRACT) {
  writeFileSync(CONTRACT_PATH, `${JSON.stringify(live, null, 2)}\n`);
}

const saved: ContentContract = JSON.parse(readFileSync(CONTRACT_PATH, 'utf8'));

const FIX = 'If this change is intended and you accept the loss, run: npm run contract:update';

describe('content contract — existing students must keep their progress', () => {
  it('keeps every level id that students have progress under', () => {
    const liveLevels = new Set(Object.keys(live.passThresholds));
    const missing = Object.keys(saved.passThresholds).filter((id) => !liveLevels.has(id));
    expect(
      missing,
      `These level ids were removed or renamed. Every student who played them loses their stars, ` +
        `the level reads as never played, and anything gated behind it re-locks. ` +
        `Prefer adding a new level id over renaming an old one. ${FIX}`,
    ).toEqual([]);
  });

  it('keeps every world id', () => {
    const liveWorlds = new Set(worlds.map((w) => w.id));
    const missing = Object.values(saved.worldsByGrade)
      .flat()
      .filter((id) => !liveWorlds.has(id));
    expect(
      missing,
      `These world ids were removed or renamed. A student parked on one loses their place on the ` +
        `map, and any badge keyed to it can never be earned. ${FIX}`,
    ).toEqual([]);
  });

  it('keeps every badge id', () => {
    const liveBadges = new Set(badges.map((b) => b.id));
    const missing = saved.badgeIds.filter((id) => !liveBadges.has(id));
    expect(
      missing,
      `These badge ids were removed or renamed. Students keep the dead id in their save, the badge ` +
        `shows as un-earned, and it can be awarded a second time. ${FIX}`,
    ).toEqual([]);
  });

  it('keeps every generator id', () => {
    const liveGenerators = new Set(allGenerators.map((g) => g.id));
    const missing = saved.generatorIds.filter((id) => !liveGenerators.has(id));
    expect(
      missing,
      `These generator ids were removed or renamed. Every student's spaced-repetition history for ` +
        `that skill is orphaned — the topic is never scheduled again, and all the boxes it had ` +
        `climbed are lost. Retiring a question type means students silently stop revising it. ${FIX}`,
    ).toEqual([]);
  });

  it('never raises a level pass mark', () => {
    // Unlocking is derived at read time from the stored bestAccuracy, so
    // raising the bar retroactively un-passes anyone sitting between the old
    // and new value — and re-locks whatever came after.
    const raised = Object.entries(saved.passThresholds)
      .filter(([id, was]) => live.passThresholds[id] !== undefined && live.passThresholds[id] > was)
      .map(([id, was]) => `${id}: ${was} → ${live.passThresholds[id]}`);
    expect(
      raised,
      `These levels became harder to pass. Unlocking is recomputed from stored accuracy every time ` +
        `it is read, so students who had already passed will find the level un-passed and the next ` +
        `one re-locked. Lowering a threshold is always safe. ${FIX}`,
    ).toEqual([]);
  });

  it('only ever appends worlds to a grade', () => {
    // isWorldUnlocked chains by index: inserting a world in the middle gates
    // every later world behind one the student has never seen.
    for (const [grade, savedOrder] of Object.entries(saved.worldsByGrade)) {
      const liveOrder = live.worldsByGrade[grade] ?? [];
      expect(
        liveOrder.slice(0, savedOrder.length),
        `Grade ${grade}'s worlds were reordered or one was inserted. World unlocking chains by ` +
          `position, so this re-locks worlds students had already opened. New worlds must go on ` +
          `the END of a grade. ${FIX}`,
      ).toEqual(savedOrder);
    }
  });

  it('only ever appends levels to a world', () => {
    for (const [worldId, savedOrder] of Object.entries(saved.levelsByWorld)) {
      const liveOrder = live.levelsByWorld[worldId];
      // A removed world is already reported by its own test; do not pile on.
      if (!liveOrder) continue;
      expect(
        liveOrder.slice(0, savedOrder.length),
        `${worldId}'s levels were reordered or one was inserted. Level unlocking chains by ` +
          `position, so this re-locks levels students had already opened. New levels must go on ` +
          `the END of a world. ${FIX}`,
      ).toEqual(savedOrder);
    }
  });
});

describe('content contract — additions stay free', () => {
  it('does not object to new content', () => {
    // Stated as a test so the intent is unmistakable: this file exists to block
    // destructive edits, not to freeze the curriculum. Everything below is new
    // since the snapshot and none of it fails anything above.
    const newLevels = Object.keys(live.passThresholds).filter(
      (id) => saved.passThresholds[id] === undefined,
    );
    const newGenerators = live.generatorIds.filter((id) => !saved.generatorIds.includes(id));
    expect(Array.isArray(newLevels)).toBe(true);
    expect(Array.isArray(newGenerators)).toBe(true);
  });
});
